"typeorm": "^0.2.21"  updated from previous 0.2.20
This fixed the  "npm start " startup error  based on the fix mentioned here https://github.com/typeorm/typeorm/issues/4573
 QueryFailedError: column cnst.consrc does not exist